--- 
services: 
  flask: 
    build: ./server
    volumes: 
      - "./server:/app"
  frontend: 
    build: ./frontend
    depends_on: 
      - flask
    links: 
      - flask
    ports: 
      - "8080:8080"
    volumes: 
      - "./frontend:/app"
      - /app/node_modules
version: "3.7"
