/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cda8aac9-f269-4d54-9df2-d6c041c3a26a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ytbitHhaE",
    "aws_user_pools_web_client_id": "58kpms90bdl6jqjso1qourrki3",
    "oauth": {}
};


export default awsmobile;
