/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3f1d7a81-d186-4b29-bd26-a22cdf538225",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Y5oaZvJDJ",
    "aws_user_pools_web_client_id": "1rq9jbeava1cee35cq6t96a2gv",
    "oauth": {}
};


export default awsmobile;
