/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cc21c786-6730-44ce-8cd0-98141ee8a358",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_baUG3B5M1",
    "aws_user_pools_web_client_id": "4trgftvk61i86larhkmdr58kfe",
    "oauth": {}
};


export default awsmobile;
